// Generated by gencpp from file motion_planning/motion_planning.msg
// DO NOT EDIT!


#ifndef MOTION_PLANNING_MESSAGE_MOTION_PLANNING_H
#define MOTION_PLANNING_MESSAGE_MOTION_PLANNING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Point.h>

namespace motion_planning
{
template <class ContainerAllocator>
struct motion_planning_
{
  typedef motion_planning_<ContainerAllocator> Type;

  motion_planning_()
    : turtlebot_twist()
    , orientation()
    , path()  {
    }
  motion_planning_(const ContainerAllocator& _alloc)
    : turtlebot_twist(_alloc)
    , orientation(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Twist_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Twist_<ContainerAllocator> >> _turtlebot_twist_type;
  _turtlebot_twist_type turtlebot_twist;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _orientation_type;
  _orientation_type orientation;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::motion_planning::motion_planning_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_planning::motion_planning_<ContainerAllocator> const> ConstPtr;

}; // struct motion_planning_

typedef ::motion_planning::motion_planning_<std::allocator<void> > motion_planning;

typedef boost::shared_ptr< ::motion_planning::motion_planning > motion_planningPtr;
typedef boost::shared_ptr< ::motion_planning::motion_planning const> motion_planningConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_planning::motion_planning_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_planning::motion_planning_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_planning::motion_planning_<ContainerAllocator1> & lhs, const ::motion_planning::motion_planning_<ContainerAllocator2> & rhs)
{
  return lhs.turtlebot_twist == rhs.turtlebot_twist &&
    lhs.orientation == rhs.orientation &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_planning::motion_planning_<ContainerAllocator1> & lhs, const ::motion_planning::motion_planning_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_planning::motion_planning_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_planning::motion_planning_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::motion_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_planning::motion_planning_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::motion_planning_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_planning::motion_planning_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_planning::motion_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0247c14c3a73b7bc94615f398d116434";
  }

  static const char* value(const ::motion_planning::motion_planning_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0247c14c3a73b7bcULL;
  static const uint64_t static_value2 = 0x94615f398d116434ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_planning::motion_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_planning/motion_planning";
  }

  static const char* value(const ::motion_planning::motion_planning_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_planning::motion_planning_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist[] turtlebot_twist\n"
"float64[] orientation\n"
"geometry_msgs/Point[] path\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::motion_planning::motion_planning_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_planning::motion_planning_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtlebot_twist);
      stream.next(m.orientation);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_planning_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_planning::motion_planning_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_planning::motion_planning_<ContainerAllocator>& v)
  {
    s << indent << "turtlebot_twist[]" << std::endl;
    for (size_t i = 0; i < v.turtlebot_twist.size(); ++i)
    {
      s << indent << "  turtlebot_twist[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "    ", v.turtlebot_twist[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_PLANNING_MESSAGE_MOTION_PLANNING_H
